import Head from "next/head";
import Script from "next/script";
import { Canvas } from "@components/index";

export default function Home({ ...pageProps }) {
  return (
    <>
      <Head>
        <title>MC - Meme Creator</title>
        <meta name="description" content="Generated by Edwin Leal" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://allfont.es/allfont.css?fonts=comic-sans-ms"
          rel="stylesheet"
          type="text/css"
        />
      </Head>
      <Script
        src="https://widget.Cloudinary.com/v2.0/global/all.js"
        type="text/javascript"
      ></Script>

      <Canvas />
    </>
  );
}
